# Database Configuration
db.url=jdbc:postgresql://localhost:5432/kids_shop
db.username=postgres
db.password=""

# Flyway Configuration
flyway.url=jdbc:postgresql://localhost:5432/kids_shop
flyway.user=postgres
flyway.password=""
flyway.locations=classpath:db/migration